function map = PsychImGuiKeymap()
% PsychImGuiKeymap  Build the PTB keycode to ImGuiKey table.
%
%   map = PsychImGuiKeymap() returns int32(256,1). Entry k holds the ImGuiKey
%   value for PTB keycode k, or 0 when the key has no Dear ImGui equivalent.
%   Pass the result to PsychImGui('Init', win, rect, map).
%
%   Psychtoolbox owns the per-platform keycode differences, so the table is
%   built from KbName('UnifyKeyNames') rather than from a table per operating
%   system inside the MEX. When Psychtoolbox is absent the function falls back
%   to the USB-HID name table that UnifyKeyNames itself targets, so the binding
%   and its tests still run.
%
%   See also PsychImGui, PsychImGuiInput.

    names = local_key_names();
    imKeys = PsychImGui('Enum');

    nameMap = local_name_map();
    map = zeros(256, 1, 'int32');
    for k = 1:256
        n = names{k};
        if isempty(n)
            continue;
        end
        key = local_lookup(nameMap, n);
        if isempty(key)
            continue;
        end
        if isfield(imKeys, key)
            map(k) = int32(imKeys.(key));
        end
    end
end

% -------------------------------------------------------------------------

function names = local_key_names()
    names = cell(256, 1);
    if exist('KbName', 'file')
        KbName('UnifyKeyNames');
        for k = 1:256
            try
                n = KbName(k);
            catch
                n = '';
            end
            if ischar(n)
                names{k} = n;
            elseif iscell(n) && ~isempty(n) && ischar(n{1})
                names{k} = n{1};
            end
        end
        return;
    end
    % Fallback: the USB-HID usage table that KbName('UnifyKeyNames') maps onto.
    hid = { ...
        4, 'a'; 5, 'b'; 6, 'c'; 7, 'd'; 8, 'e'; 9, 'f'; 10, 'g'; 11, 'h'; ...
        12, 'i'; 13, 'j'; 14, 'k'; 15, 'l'; 16, 'm'; 17, 'n'; 18, 'o'; 19, 'p'; ...
        20, 'q'; 21, 'r'; 22, 's'; 23, 't'; 24, 'u'; 25, 'v'; 26, 'w'; 27, 'x'; ...
        28, 'y'; 29, 'z'; ...
        30, '1!'; 31, '2@'; 32, '3#'; 33, '4$'; 34, '5%'; 35, '6^'; 36, '7&'; ...
        37, '8*'; 38, '9('; 39, '0)'; ...
        40, 'Return'; 41, 'ESCAPE'; 42, 'DELETE'; 43, 'tab'; 44, 'space'; ...
        45, '-_'; 46, '=+'; 47, '[{'; 48, ']}'; 49, '\|'; 51, ';:'; 52, '''"'; ...
        53, '`~'; 54, ',<'; 55, '.>'; 56, '/?'; 57, 'CapsLock'; ...
        58, 'F1'; 59, 'F2'; 60, 'F3'; 61, 'F4'; 62, 'F5'; 63, 'F6'; 64, 'F7'; ...
        65, 'F8'; 66, 'F9'; 67, 'F10'; 68, 'F11'; 69, 'F12'; ...
        70, 'PrintScreen'; 71, 'ScrollLock'; 72, 'Pause'; 73, 'Insert'; ...
        74, 'Home'; 75, 'PageUp'; 76, 'DeleteForward'; 77, 'End'; 78, 'PageDown'; ...
        79, 'RightArrow'; 80, 'LeftArrow'; 81, 'DownArrow'; 82, 'UpArrow'; ...
        83, 'NumLockClear'; 84, '/'; 85, '*'; 86, '-'; 87, '+'; 88, 'ENTER'; ...
        89, '1'; 90, '2'; 91, '3'; 92, '4'; 93, '5'; 94, '6'; 95, '7'; 96, '8'; ...
        97, '9'; 98, '0'; 99, '.'; 101, 'Application'; 103, '='; ...
        104, 'F13'; 105, 'F14'; 106, 'F15'; 107, 'F16'; 108, 'F17'; 109, 'F18'; ...
        110, 'F19'; 111, 'F20'; 112, 'F21'; 113, 'F22'; 114, 'F23'; 115, 'F24'; ...
        224, 'LeftControl'; 225, 'LeftShift'; 226, 'LeftAlt'; 227, 'LeftGUI'; ...
        228, 'RightControl'; 229, 'RightShift'; 230, 'RightAlt'; 231, 'RightGUI'};
    for i = 1:size(hid, 1)
        names{hid{i, 1}} = hid{i, 2};
    end
end

function m = local_name_map()
% Two column cell array: PTB unified name, ImGuiKey name.
    letters = cell(26, 2);
    for i = 1:26
        letters{i, 1} = char('a' + i - 1);
        letters{i, 2} = ['ImGuiKey_' upper(char('a' + i - 1))];
    end
    digits = {'1!', 'ImGuiKey_1'; '2@', 'ImGuiKey_2'; '3#', 'ImGuiKey_3'; ...
              '4$', 'ImGuiKey_4'; '5%', 'ImGuiKey_5'; '6^', 'ImGuiKey_6'; ...
              '7&', 'ImGuiKey_7'; '8*', 'ImGuiKey_8'; '9(', 'ImGuiKey_9'; ...
              '0)', 'ImGuiKey_0'};
    fkeys = cell(24, 2);
    for i = 1:24
        fkeys{i, 1} = sprintf('F%d', i);
        fkeys{i, 2} = sprintf('ImGuiKey_F%d', i);
    end
    keypadDigits = cell(10, 2);
    for i = 0:9
        keypadDigits{i + 1, 1} = sprintf('%d', i);
        keypadDigits{i + 1, 2} = sprintf('ImGuiKey_Keypad%d', i);
    end

    % PTB calls USB-HID usage 42 "DELETE", which is the Backspace key, while
    % the Windows and Linux tables use "DELETE" for the forward delete key.
    if ismac
        deleteKey = 'ImGuiKey_Backspace';
    else
        deleteKey = 'ImGuiKey_Delete';
    end

    rest = { ...
        'Return', 'ImGuiKey_Enter'; 'ENTER', 'ImGuiKey_KeypadEnter'; ...
        'ESCAPE', 'ImGuiKey_Escape'; 'esc', 'ImGuiKey_Escape'; ...
        'DELETE', deleteKey; 'BackSpace', 'ImGuiKey_Backspace'; ...
        'backspace', 'ImGuiKey_Backspace'; 'DeleteForward', 'ImGuiKey_Delete'; ...
        'tab', 'ImGuiKey_Tab'; 'space', 'ImGuiKey_Space'; ...
        '-_', 'ImGuiKey_Minus'; '=+', 'ImGuiKey_Equal'; ...
        '[{', 'ImGuiKey_LeftBracket'; ']}', 'ImGuiKey_RightBracket'; ...
        '[', 'ImGuiKey_LeftBracket'; ']', 'ImGuiKey_RightBracket'; ...
        '\|', 'ImGuiKey_Backslash'; '\\', 'ImGuiKey_Backslash'; ...
        ';:', 'ImGuiKey_Semicolon'; ';', 'ImGuiKey_Semicolon'; ...
        '''"', 'ImGuiKey_Apostrophe'; '''', 'ImGuiKey_Apostrophe'; ...
        '`~', 'ImGuiKey_GraveAccent'; '`', 'ImGuiKey_GraveAccent'; ...
        ',<', 'ImGuiKey_Comma'; '.>', 'ImGuiKey_Period'; '/?', 'ImGuiKey_Slash'; ...
        'CapsLock', 'ImGuiKey_CapsLock'; 'capslock', 'ImGuiKey_CapsLock'; ...
        'PrintScreen', 'ImGuiKey_PrintScreen'; 'ScrollLock', 'ImGuiKey_ScrollLock'; ...
        'scrolllock', 'ImGuiKey_ScrollLock'; 'Pause', 'ImGuiKey_Pause'; ...
        'Insert', 'ImGuiKey_Insert'; 'insert', 'ImGuiKey_Insert'; ...
        'Home', 'ImGuiKey_Home'; 'home', 'ImGuiKey_Home'; ...
        'PageUp', 'ImGuiKey_PageUp'; 'pageup', 'ImGuiKey_PageUp'; ...
        'End', 'ImGuiKey_End'; 'end', 'ImGuiKey_End'; ...
        'PageDown', 'ImGuiKey_PageDown'; 'pagedown', 'ImGuiKey_PageDown'; ...
        'RightArrow', 'ImGuiKey_RightArrow'; 'LeftArrow', 'ImGuiKey_LeftArrow'; ...
        'DownArrow', 'ImGuiKey_DownArrow'; 'UpArrow', 'ImGuiKey_UpArrow'; ...
        'right', 'ImGuiKey_RightArrow'; 'left', 'ImGuiKey_LeftArrow'; ...
        'down', 'ImGuiKey_DownArrow'; 'up', 'ImGuiKey_UpArrow'; ...
        'NumLockClear', 'ImGuiKey_NumLock'; 'NumLock', 'ImGuiKey_NumLock'; ...
        'numlock', 'ImGuiKey_NumLock'; ...
        '/', 'ImGuiKey_KeypadDivide'; '*', 'ImGuiKey_KeypadMultiply'; ...
        '-', 'ImGuiKey_KeypadSubtract'; '+', 'ImGuiKey_KeypadAdd'; ...
        '.', 'ImGuiKey_KeypadDecimal'; '=', 'ImGuiKey_KeypadEqual'; ...
        'Application', 'ImGuiKey_Menu'; 'Menu', 'ImGuiKey_Menu'; ...
        'applications', 'ImGuiKey_Menu'; ...
        'LeftControl', 'ImGuiKey_LeftCtrl'; 'RightControl', 'ImGuiKey_RightCtrl'; ...
        'left_control', 'ImGuiKey_LeftCtrl'; 'right_control', 'ImGuiKey_RightCtrl'; ...
        'LeftShift', 'ImGuiKey_LeftShift'; 'RightShift', 'ImGuiKey_RightShift'; ...
        'left_shift', 'ImGuiKey_LeftShift'; 'right_shift', 'ImGuiKey_RightShift'; ...
        'LeftAlt', 'ImGuiKey_LeftAlt'; 'RightAlt', 'ImGuiKey_RightAlt'; ...
        'LeftGUI', 'ImGuiKey_LeftSuper'; 'RightGUI', 'ImGuiKey_RightSuper'; ...
        'Shift', 'ImGuiKey_LeftShift'; 'shift', 'ImGuiKey_LeftShift'; ...
        'control', 'ImGuiKey_LeftCtrl'; 'alt', 'ImGuiKey_LeftAlt'};

    m = [letters; digits; fkeys; keypadDigits; rest];
end

function key = local_lookup(nameMap, n)
    key = '';
    for i = 1:size(nameMap, 1)
        if strcmp(nameMap{i, 1}, n)
            key = nameMap{i, 2};
            return;
        end
    end
end
