// GENERATED by gen/generate.py from the cimgui metadata. Do not edit by hand.
// Dear ImGui 1.92.9b, ImPlot3D 0.4

#ifdef PSYCHIMGUI_IMPLOT3D
#include "imgui_psych.h"

#include "marshal.h"
#include "dispatch.h"
#include "implot3d_marshal.h"

// Its own namespace: a few subcommand names exist in several namespaces,
// and the handlers need external linkage for the shared dispatch table.
namespace pig_implot3d {

extern const char kSig_BeginPlot[] =
    "open = PsychImGui('ImPlot3D.BeginPlot', titleId [, size=[-1 0]] [, flags=0])";
void h_BeginPlot(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin < 1 || nargin > 3) { mrs::usage("BeginPlot", kSig_BeginPlot); return; }
    (void)nlhs; (void)plhs; (void)args;
    mrs::StrBuf<256> b_title_id;
    const char* v_title_id = "";
    v_title_id = mrs::toUtf8(args[0], "titleId", b_title_id);
    ImVec2 v_size = ImVec2(-1,0);
    if (nargin > 1) { double t[2] = {0, 0}; mrs::getVec(args[1], "size", t, 2); v_size = ImVec2((float)t[0], (float)t[1]); }
    ImPlot3DFlags v_flags = (ImPlot3DFlags)(0);
    if (nargin > 2) v_flags = (ImPlot3DFlags)mrs::getFlags(args[2], "flags");
    if (mrs::failed()) return;
    bool ret = ImPlot3D::BeginPlot(v_title_id, v_size, v_flags);
    if (nlhs > 0) plhs[0] = mrs::outBool(ret);
}

extern const char kSig_EndPlot[] =
    "PsychImGui('ImPlot3D.EndPlot')";
void h_EndPlot(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin != 0) { mrs::usage("EndPlot", kSig_EndPlot); return; }
    (void)nlhs; (void)plhs; (void)args;
    if (mrs::failed()) return;
    ImPlot3D::EndPlot();
}

extern const char kSig_SetupAxis[] =
    "PsychImGui('ImPlot3D.SetupAxis', axis [, label=[]] [, flags=0])";
void h_SetupAxis(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin < 1 || nargin > 3) { mrs::usage("SetupAxis", kSig_SetupAxis); return; }
    (void)nlhs; (void)plhs; (void)args;
    ImAxis3D v_axis = (ImAxis3D)(0);
    v_axis = (ImAxis3D)mrs::getFlags(args[0], "axis");
    mrs::StrBuf<256> b_label;
    const char* v_label = NULL;
    if (nargin > 1 && !mxIsEmpty(args[1])) v_label = mrs::toUtf8(args[1], "label", b_label);
    ImPlot3DAxisFlags v_flags = (ImPlot3DAxisFlags)(0);
    if (nargin > 2) v_flags = (ImPlot3DAxisFlags)mrs::getFlags(args[2], "flags");
    if (mrs::failed()) return;
    if (!mrs::implot3dPlotOpen()) { mrs::fail("psychimgui:Usage", "ImPlot3D.SetupAxis needs an open plot: call it between ImPlot3D.BeginPlot and ImPlot3D.EndPlot."); return; }
    ImPlot3D::SetupAxis(v_axis, v_label, v_flags);
}

extern const char kSig_SetupAxes[] =
    "PsychImGui('ImPlot3D.SetupAxes', xLabel, yLabel, zLabel [, xFlags=0] [, yFlags=0] [, zFlags=0])";
void h_SetupAxes(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin < 3 || nargin > 6) { mrs::usage("SetupAxes", kSig_SetupAxes); return; }
    (void)nlhs; (void)plhs; (void)args;
    mrs::StrBuf<256> b_x_label;
    const char* v_x_label = "";
    v_x_label = mrs::toUtf8(args[0], "xLabel", b_x_label);
    mrs::StrBuf<256> b_y_label;
    const char* v_y_label = "";
    v_y_label = mrs::toUtf8(args[1], "yLabel", b_y_label);
    mrs::StrBuf<256> b_z_label;
    const char* v_z_label = "";
    v_z_label = mrs::toUtf8(args[2], "zLabel", b_z_label);
    ImPlot3DAxisFlags v_x_flags = (ImPlot3DAxisFlags)(0);
    if (nargin > 3) v_x_flags = (ImPlot3DAxisFlags)mrs::getFlags(args[3], "xFlags");
    ImPlot3DAxisFlags v_y_flags = (ImPlot3DAxisFlags)(0);
    if (nargin > 4) v_y_flags = (ImPlot3DAxisFlags)mrs::getFlags(args[4], "yFlags");
    ImPlot3DAxisFlags v_z_flags = (ImPlot3DAxisFlags)(0);
    if (nargin > 5) v_z_flags = (ImPlot3DAxisFlags)mrs::getFlags(args[5], "zFlags");
    if (mrs::failed()) return;
    if (!mrs::implot3dPlotOpen()) { mrs::fail("psychimgui:Usage", "ImPlot3D.SetupAxes needs an open plot: call it between ImPlot3D.BeginPlot and ImPlot3D.EndPlot."); return; }
    ImPlot3D::SetupAxes(v_x_label, v_y_label, v_z_label, v_x_flags, v_y_flags, v_z_flags);
}

extern const char kSig_SetupAxisLimits[] =
    "PsychImGui('ImPlot3D.SetupAxisLimits', axis, vMin, vMax [, cond=ImPlot3DCond_Once])";
void h_SetupAxisLimits(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin < 3 || nargin > 4) { mrs::usage("SetupAxisLimits", kSig_SetupAxisLimits); return; }
    (void)nlhs; (void)plhs; (void)args;
    ImAxis3D v_axis = (ImAxis3D)(0);
    v_axis = (ImAxis3D)mrs::getFlags(args[0], "axis");
    double v_v_min = (double)(0);
    v_v_min = (double)mrs::getScalar(args[1], "vMin");
    double v_v_max = (double)(0);
    v_v_max = (double)mrs::getScalar(args[2], "vMax");
    ImPlot3DCond v_cond = (ImPlot3DCond)(ImPlot3DCond_Once);
    if (nargin > 3) v_cond = (ImPlot3DCond)mrs::getFlags(args[3], "cond");
    if (mrs::failed()) return;
    if (!mrs::implot3dPlotOpen()) { mrs::fail("psychimgui:Usage", "ImPlot3D.SetupAxisLimits needs an open plot: call it between ImPlot3D.BeginPlot and ImPlot3D.EndPlot."); return; }
    ImPlot3D::SetupAxisLimits(v_axis, v_v_min, v_v_max, v_cond);
}

extern const char kSig_SetupAxesLimits[] =
    "PsychImGui('ImPlot3D.SetupAxesLimits', xMin, xMax, yMin, yMax, zMin, zMax [, cond=ImPlot3DCond_Once])";
void h_SetupAxesLimits(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin < 6 || nargin > 7) { mrs::usage("SetupAxesLimits", kSig_SetupAxesLimits); return; }
    (void)nlhs; (void)plhs; (void)args;
    double v_x_min = (double)(0);
    v_x_min = (double)mrs::getScalar(args[0], "xMin");
    double v_x_max = (double)(0);
    v_x_max = (double)mrs::getScalar(args[1], "xMax");
    double v_y_min = (double)(0);
    v_y_min = (double)mrs::getScalar(args[2], "yMin");
    double v_y_max = (double)(0);
    v_y_max = (double)mrs::getScalar(args[3], "yMax");
    double v_z_min = (double)(0);
    v_z_min = (double)mrs::getScalar(args[4], "zMin");
    double v_z_max = (double)(0);
    v_z_max = (double)mrs::getScalar(args[5], "zMax");
    ImPlot3DCond v_cond = (ImPlot3DCond)(ImPlot3DCond_Once);
    if (nargin > 6) v_cond = (ImPlot3DCond)mrs::getFlags(args[6], "cond");
    if (mrs::failed()) return;
    if (!mrs::implot3dPlotOpen()) { mrs::fail("psychimgui:Usage", "ImPlot3D.SetupAxesLimits needs an open plot: call it between ImPlot3D.BeginPlot and ImPlot3D.EndPlot."); return; }
    ImPlot3D::SetupAxesLimits(v_x_min, v_x_max, v_y_min, v_y_max, v_z_min, v_z_max, v_cond);
}

extern const char kSig_SetupAxisTicks[] =
    "PsychImGui('ImPlot3D.SetupAxisTicks', axis, values [, labels=[]] [, keepDefault=false])";
void h_SetupAxisTicks(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin < 2 || nargin > 4) { mrs::usage("SetupAxisTicks", kSig_SetupAxisTicks); return; }
    (void)nlhs; (void)plhs; (void)args;
    ImAxis3D v_axis = (ImAxis3D)(0);
    v_axis = (ImAxis3D)mrs::getFlags(args[0], "axis");
    int n_values = 0;
    const double* v_values = mrs::getDoubleArray(args[1], "values", &n_values);
    mrs::CellStr cs_labels;
    const char* const* v_labels = NULL;
    if (nargin > 2 && !mxIsEmpty(args[2])) v_labels = mrs::getCellStr(args[2], "labels", cs_labels);
    if (v_labels && cs_labels.n != n_values) {
        mrs::fail("psychimgui:Usage", "labels must have the same number of entries as the values array (%d, not %d).", n_values, cs_labels.n);
        return;
    }
    bool v_keep_default = false;
    if (nargin > 3) v_keep_default = mrs::getBool(args[3], "keepDefault");
    if (mrs::failed()) return;
    if (!mrs::implot3dPlotOpen()) { mrs::fail("psychimgui:Usage", "ImPlot3D.SetupAxisTicks needs an open plot: call it between ImPlot3D.BeginPlot and ImPlot3D.EndPlot."); return; }
    ImPlot3D::SetupAxisTicks(v_axis, v_values, n_values, v_labels, v_keep_default);
}

extern const char kSig_SetupBoxRotation[] =
    "PsychImGui('ImPlot3D.SetupBoxRotation', elevation, azimuth [, animate=false] [, cond=ImPlot3DCond_Once])";
void h_SetupBoxRotation(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin < 2 || nargin > 4) { mrs::usage("SetupBoxRotation", kSig_SetupBoxRotation); return; }
    (void)nlhs; (void)plhs; (void)args;
    double v_elevation = (double)(0);
    v_elevation = (double)mrs::getScalar(args[0], "elevation");
    double v_azimuth = (double)(0);
    v_azimuth = (double)mrs::getScalar(args[1], "azimuth");
    bool v_animate = false;
    if (nargin > 2) v_animate = mrs::getBool(args[2], "animate");
    ImPlot3DCond v_cond = (ImPlot3DCond)(ImPlot3DCond_Once);
    if (nargin > 3) v_cond = (ImPlot3DCond)mrs::getFlags(args[3], "cond");
    if (mrs::failed()) return;
    if (!mrs::implot3dPlotOpen()) { mrs::fail("psychimgui:Usage", "ImPlot3D.SetupBoxRotation needs an open plot: call it between ImPlot3D.BeginPlot and ImPlot3D.EndPlot."); return; }
    ImPlot3D::SetupBoxRotation(v_elevation, v_azimuth, v_animate, v_cond);
}

extern const char kSig_SetupBoxScale[] =
    "PsychImGui('ImPlot3D.SetupBoxScale', x, y, z)";
void h_SetupBoxScale(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin < 3 || nargin > 3) { mrs::usage("SetupBoxScale", kSig_SetupBoxScale); return; }
    (void)nlhs; (void)plhs; (void)args;
    double v_x = (double)(0);
    v_x = (double)mrs::getScalar(args[0], "x");
    double v_y = (double)(0);
    v_y = (double)mrs::getScalar(args[1], "y");
    double v_z = (double)(0);
    v_z = (double)mrs::getScalar(args[2], "z");
    if (mrs::failed()) return;
    if (!mrs::implot3dPlotOpen()) { mrs::fail("psychimgui:Usage", "ImPlot3D.SetupBoxScale needs an open plot: call it between ImPlot3D.BeginPlot and ImPlot3D.EndPlot."); return; }
    if (!(v_x > 0.0 && v_y > 0.0 && v_z > 0.0)) { mrs::fail("psychimgui:Range", "SetupBoxScale: x, y, and z must be greater than 0, got %g, %g, %g.", v_x, v_y, v_z); return; }
    ImPlot3D::SetupBoxScale(v_x, v_y, v_z);
}

extern const char kSig_SetupLegend[] =
    "PsychImGui('ImPlot3D.SetupLegend', location [, flags=0])";
void h_SetupLegend(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin < 1 || nargin > 2) { mrs::usage("SetupLegend", kSig_SetupLegend); return; }
    (void)nlhs; (void)plhs; (void)args;
    ImPlot3DLocation v_location = (ImPlot3DLocation)(0);
    v_location = (ImPlot3DLocation)mrs::getFlags(args[0], "location");
    ImPlot3DLegendFlags v_flags = (ImPlot3DLegendFlags)(0);
    if (nargin > 1) v_flags = (ImPlot3DLegendFlags)mrs::getFlags(args[1], "flags");
    if (mrs::failed()) return;
    if (!mrs::implot3dPlotOpen()) { mrs::fail("psychimgui:Usage", "ImPlot3D.SetupLegend needs an open plot: call it between ImPlot3D.BeginPlot and ImPlot3D.EndPlot."); return; }
    ImPlot3D::SetupLegend(v_location, v_flags);
}

extern const char kSig_PlotLine[] =
    "PsychImGui('ImPlot3D.PlotLine', labelId, xs, ys, zs [, spec...])";
template <typename T_>
static void tp_PlotLine_3(int nlhs, mxArray** plhs, const char* v_label, const mxArray** args, int nargin, int specAt, int count) {
    (void)nlhs; (void)plhs;
    ImPlot3DSpec v_spec;
    mrs::getSpec(args, nargin, specAt, v_spec, sizeof(T_));
    if (mrs::failed()) return;
    ImPlot3D::PlotLine(v_label, (const T_*)mxGetData(args[1]), (const T_*)mxGetData(args[2]), (const T_*)mxGetData(args[3]), count, v_spec);
}

void h_PlotLine(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin < 2) { mrs::usage("ImPlot3D.PlotLine", kSig_PlotLine); return; }
    if (!mrs::implot3dPlotOpen()) { mrs::fail("psychimgui:Usage", "ImPlot3D.PlotLine needs an open plot: call it between ImPlot3D.BeginPlot and ImPlot3D.EndPlot."); return; }
    mrs::StrBuf<256> b_label;
    const char* v_label = mrs::toUtf8(args[0], "labelId", b_label);
    int nData = mrs::dataArgCount(args, nargin, 1, 3);
    int count = 0;
    mxClassID cid = mrs::checkData(args, 1, nData, "ImPlot3D.PlotLine", &count);
    if (mrs::failed()) return;
    if (nData == 3) {
        int specAt = mrs::specStart3D(args, nargin, 4);
        if (mrs::failed()) return;
        switch (cid) {
        case mxDOUBLE_CLASS: tp_PlotLine_3<double>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxSINGLE_CLASS: tp_PlotLine_3<float>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxINT8_CLASS: tp_PlotLine_3<ImS8>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxUINT8_CLASS: tp_PlotLine_3<ImU8>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxINT16_CLASS: tp_PlotLine_3<ImS16>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxUINT16_CLASS: tp_PlotLine_3<ImU16>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxINT32_CLASS: tp_PlotLine_3<ImS32>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxUINT32_CLASS: tp_PlotLine_3<ImU32>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxINT64_CLASS: tp_PlotLine_3<ImS64>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxUINT64_CLASS: tp_PlotLine_3<ImU64>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        default: mrs::fail("psychimgui:Type", "ImPlot3D.PlotLine: unsupported data class."); break;
        }
    } else {
        mrs::usage("ImPlot3D.PlotLine", kSig_PlotLine);
    }
}

extern const char kSig_PlotScatter[] =
    "PsychImGui('ImPlot3D.PlotScatter', labelId, xs, ys, zs [, spec...])";
template <typename T_>
static void tp_PlotScatter_3(int nlhs, mxArray** plhs, const char* v_label, const mxArray** args, int nargin, int specAt, int count) {
    (void)nlhs; (void)plhs;
    ImPlot3DSpec v_spec;
    mrs::getSpec(args, nargin, specAt, v_spec, sizeof(T_));
    if (mrs::failed()) return;
    ImPlot3D::PlotScatter(v_label, (const T_*)mxGetData(args[1]), (const T_*)mxGetData(args[2]), (const T_*)mxGetData(args[3]), count, v_spec);
}

void h_PlotScatter(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin < 2) { mrs::usage("ImPlot3D.PlotScatter", kSig_PlotScatter); return; }
    if (!mrs::implot3dPlotOpen()) { mrs::fail("psychimgui:Usage", "ImPlot3D.PlotScatter needs an open plot: call it between ImPlot3D.BeginPlot and ImPlot3D.EndPlot."); return; }
    mrs::StrBuf<256> b_label;
    const char* v_label = mrs::toUtf8(args[0], "labelId", b_label);
    int nData = mrs::dataArgCount(args, nargin, 1, 3);
    int count = 0;
    mxClassID cid = mrs::checkData(args, 1, nData, "ImPlot3D.PlotScatter", &count);
    if (mrs::failed()) return;
    if (nData == 3) {
        int specAt = mrs::specStart3D(args, nargin, 4);
        if (mrs::failed()) return;
        switch (cid) {
        case mxDOUBLE_CLASS: tp_PlotScatter_3<double>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxSINGLE_CLASS: tp_PlotScatter_3<float>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxINT8_CLASS: tp_PlotScatter_3<ImS8>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxUINT8_CLASS: tp_PlotScatter_3<ImU8>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxINT16_CLASS: tp_PlotScatter_3<ImS16>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxUINT16_CLASS: tp_PlotScatter_3<ImU16>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxINT32_CLASS: tp_PlotScatter_3<ImS32>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxUINT32_CLASS: tp_PlotScatter_3<ImU32>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxINT64_CLASS: tp_PlotScatter_3<ImS64>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxUINT64_CLASS: tp_PlotScatter_3<ImU64>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        default: mrs::fail("psychimgui:Type", "ImPlot3D.PlotScatter: unsupported data class."); break;
        }
    } else {
        mrs::usage("ImPlot3D.PlotScatter", kSig_PlotScatter);
    }
}

extern const char kSig_PlotTriangle[] =
    "PsychImGui('ImPlot3D.PlotTriangle', labelId, xs, ys, zs [, spec...])";
template <typename T_>
static void tp_PlotTriangle_3(int nlhs, mxArray** plhs, const char* v_label, const mxArray** args, int nargin, int specAt, int count) {
    (void)nlhs; (void)plhs;
    ImPlot3DSpec v_spec;
    mrs::getSpec(args, nargin, specAt, v_spec, sizeof(T_));
    if (mrs::failed()) return;
    ImPlot3D::PlotTriangle(v_label, (const T_*)mxGetData(args[1]), (const T_*)mxGetData(args[2]), (const T_*)mxGetData(args[3]), count, v_spec);
}

void h_PlotTriangle(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin < 2) { mrs::usage("ImPlot3D.PlotTriangle", kSig_PlotTriangle); return; }
    if (!mrs::implot3dPlotOpen()) { mrs::fail("psychimgui:Usage", "ImPlot3D.PlotTriangle needs an open plot: call it between ImPlot3D.BeginPlot and ImPlot3D.EndPlot."); return; }
    mrs::StrBuf<256> b_label;
    const char* v_label = mrs::toUtf8(args[0], "labelId", b_label);
    int nData = mrs::dataArgCount(args, nargin, 1, 3);
    int count = 0;
    mxClassID cid = mrs::checkData(args, 1, nData, "ImPlot3D.PlotTriangle", &count);
    if (mrs::failed()) return;
    if (nData == 3) {
        int specAt = mrs::specStart3D(args, nargin, 4);
        if (mrs::failed()) return;
        switch (cid) {
        case mxDOUBLE_CLASS: tp_PlotTriangle_3<double>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxSINGLE_CLASS: tp_PlotTriangle_3<float>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxINT8_CLASS: tp_PlotTriangle_3<ImS8>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxUINT8_CLASS: tp_PlotTriangle_3<ImU8>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxINT16_CLASS: tp_PlotTriangle_3<ImS16>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxUINT16_CLASS: tp_PlotTriangle_3<ImU16>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxINT32_CLASS: tp_PlotTriangle_3<ImS32>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxUINT32_CLASS: tp_PlotTriangle_3<ImU32>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxINT64_CLASS: tp_PlotTriangle_3<ImS64>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxUINT64_CLASS: tp_PlotTriangle_3<ImU64>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        default: mrs::fail("psychimgui:Type", "ImPlot3D.PlotTriangle: unsupported data class."); break;
        }
    } else {
        mrs::usage("ImPlot3D.PlotTriangle", kSig_PlotTriangle);
    }
}

extern const char kSig_PlotQuad[] =
    "PsychImGui('ImPlot3D.PlotQuad', labelId, xs, ys, zs [, spec...])";
template <typename T_>
static void tp_PlotQuad_3(int nlhs, mxArray** plhs, const char* v_label, const mxArray** args, int nargin, int specAt, int count) {
    (void)nlhs; (void)plhs;
    ImPlot3DSpec v_spec;
    mrs::getSpec(args, nargin, specAt, v_spec, sizeof(T_));
    if (mrs::failed()) return;
    ImPlot3D::PlotQuad(v_label, (const T_*)mxGetData(args[1]), (const T_*)mxGetData(args[2]), (const T_*)mxGetData(args[3]), count, v_spec);
}

void h_PlotQuad(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin < 2) { mrs::usage("ImPlot3D.PlotQuad", kSig_PlotQuad); return; }
    if (!mrs::implot3dPlotOpen()) { mrs::fail("psychimgui:Usage", "ImPlot3D.PlotQuad needs an open plot: call it between ImPlot3D.BeginPlot and ImPlot3D.EndPlot."); return; }
    mrs::StrBuf<256> b_label;
    const char* v_label = mrs::toUtf8(args[0], "labelId", b_label);
    int nData = mrs::dataArgCount(args, nargin, 1, 3);
    int count = 0;
    mxClassID cid = mrs::checkData(args, 1, nData, "ImPlot3D.PlotQuad", &count);
    if (mrs::failed()) return;
    if (nData == 3) {
        int specAt = mrs::specStart3D(args, nargin, 4);
        if (mrs::failed()) return;
        switch (cid) {
        case mxDOUBLE_CLASS: tp_PlotQuad_3<double>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxSINGLE_CLASS: tp_PlotQuad_3<float>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxINT8_CLASS: tp_PlotQuad_3<ImS8>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxUINT8_CLASS: tp_PlotQuad_3<ImU8>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxINT16_CLASS: tp_PlotQuad_3<ImS16>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxUINT16_CLASS: tp_PlotQuad_3<ImU16>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxINT32_CLASS: tp_PlotQuad_3<ImS32>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxUINT32_CLASS: tp_PlotQuad_3<ImU32>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxINT64_CLASS: tp_PlotQuad_3<ImS64>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        case mxUINT64_CLASS: tp_PlotQuad_3<ImU64>(nlhs, plhs, v_label, args, nargin, specAt, count); break;
        default: mrs::fail("psychimgui:Type", "ImPlot3D.PlotQuad: unsupported data class."); break;
        }
    } else {
        mrs::usage("ImPlot3D.PlotQuad", kSig_PlotQuad);
    }
}

extern const char kSig_PlotSurface[] =
    "PsychImGui('ImPlot3D.PlotSurface', labelId, X, Y, Z [, scaleMin=0.0] [, scaleMax=0.0] [, spec...])";
template <typename T_>
static void tp_PlotSurface_3(int nlhs, mxArray** plhs, const char* v_label, const mxArray** args, int nargin, int specAt, int xCount, int yCount, double v_scale_min, double v_scale_max) {
    (void)nlhs; (void)plhs;
    ImPlot3DSpec v_spec;
    mrs::getSpec(args, nargin, specAt, v_spec, sizeof(T_));
    if (mrs::failed()) return;
    ImPlot3D::PlotSurface(v_label, (const T_*)mxGetData(args[1]), (const T_*)mxGetData(args[2]), (const T_*)mxGetData(args[3]), xCount, yCount, v_scale_min, v_scale_max, v_spec);
}

void h_PlotSurface(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin < 2) { mrs::usage("ImPlot3D.PlotSurface", kSig_PlotSurface); return; }
    if (!mrs::implot3dPlotOpen()) { mrs::fail("psychimgui:Usage", "ImPlot3D.PlotSurface needs an open plot: call it between ImPlot3D.BeginPlot and ImPlot3D.EndPlot."); return; }
    mrs::StrBuf<256> b_label;
    const char* v_label = mrs::toUtf8(args[0], "labelId", b_label);
    int nData = mrs::dataArgCount(args, nargin, 1, 3);
    int count = 0;
    mxClassID cid = mrs::checkData(args, 1, nData, "ImPlot3D.PlotSurface", &count);
    if (mrs::failed()) return;
    if (nData == 3) {
        int specAt = mrs::specStart3D(args, nargin, 4);
        // A grid from meshgrid is column major, so its first dimension
        // is the one that varies fastest, which is ImPlot3D's x.
        int xCount = (int)mxGetM(args[1]);
        int yCount = (int)mxGetN(args[1]);
        double v_scale_min = (double)(0.0);
        if (nargin > 4 && 4 < specAt) v_scale_min = (double)mrs::getScalar(args[4], "scaleMin");
        double v_scale_max = (double)(0.0);
        if (nargin > 5 && 5 < specAt) v_scale_max = (double)mrs::getScalar(args[5], "scaleMax");
        if (mrs::failed()) return;
        switch (cid) {
        case mxDOUBLE_CLASS: tp_PlotSurface_3<double>(nlhs, plhs, v_label, args, nargin, specAt, xCount, yCount, v_scale_min, v_scale_max); break;
        case mxSINGLE_CLASS: tp_PlotSurface_3<float>(nlhs, plhs, v_label, args, nargin, specAt, xCount, yCount, v_scale_min, v_scale_max); break;
        case mxINT8_CLASS: tp_PlotSurface_3<ImS8>(nlhs, plhs, v_label, args, nargin, specAt, xCount, yCount, v_scale_min, v_scale_max); break;
        case mxUINT8_CLASS: tp_PlotSurface_3<ImU8>(nlhs, plhs, v_label, args, nargin, specAt, xCount, yCount, v_scale_min, v_scale_max); break;
        case mxINT16_CLASS: tp_PlotSurface_3<ImS16>(nlhs, plhs, v_label, args, nargin, specAt, xCount, yCount, v_scale_min, v_scale_max); break;
        case mxUINT16_CLASS: tp_PlotSurface_3<ImU16>(nlhs, plhs, v_label, args, nargin, specAt, xCount, yCount, v_scale_min, v_scale_max); break;
        case mxINT32_CLASS: tp_PlotSurface_3<ImS32>(nlhs, plhs, v_label, args, nargin, specAt, xCount, yCount, v_scale_min, v_scale_max); break;
        case mxUINT32_CLASS: tp_PlotSurface_3<ImU32>(nlhs, plhs, v_label, args, nargin, specAt, xCount, yCount, v_scale_min, v_scale_max); break;
        case mxINT64_CLASS: tp_PlotSurface_3<ImS64>(nlhs, plhs, v_label, args, nargin, specAt, xCount, yCount, v_scale_min, v_scale_max); break;
        case mxUINT64_CLASS: tp_PlotSurface_3<ImU64>(nlhs, plhs, v_label, args, nargin, specAt, xCount, yCount, v_scale_min, v_scale_max); break;
        default: mrs::fail("psychimgui:Type", "ImPlot3D.PlotSurface: unsupported data class."); break;
        }
    } else {
        mrs::usage("ImPlot3D.PlotSurface", kSig_PlotSurface);
    }
}

extern const char kSig_PlotMesh[] =
    "PsychImGui('ImPlot3D.PlotMesh', labelId, xs, ys, zs, faces [, spec...])";
template <typename T_>
static void tp_PlotMesh_3(int nlhs, mxArray** plhs, const char* v_label, const mxArray** args, int nargin, int specAt, int count, const unsigned* v_faces, int idxCount) {
    (void)nlhs; (void)plhs;
    ImPlot3DSpec v_spec;
    mrs::getSpec(args, nargin, specAt, v_spec, sizeof(T_));
    if (mrs::failed()) return;
    ImPlot3D::PlotMesh(v_label, (const T_*)mxGetData(args[1]), (const T_*)mxGetData(args[2]), (const T_*)mxGetData(args[3]), v_faces, count, idxCount, v_spec);
}

void h_PlotMesh(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin < 2) { mrs::usage("ImPlot3D.PlotMesh", kSig_PlotMesh); return; }
    if (!mrs::implot3dPlotOpen()) { mrs::fail("psychimgui:Usage", "ImPlot3D.PlotMesh needs an open plot: call it between ImPlot3D.BeginPlot and ImPlot3D.EndPlot."); return; }
    mrs::StrBuf<256> b_label;
    const char* v_label = mrs::toUtf8(args[0], "labelId", b_label);
    int nData = mrs::dataArgCount(args, nargin, 1, 3);
    int count = 0;
    mxClassID cid = mrs::checkData(args, 1, nData, "ImPlot3D.PlotMesh", &count);
    if (mrs::failed()) return;
    if (nData == 3) {
        int specAt = mrs::specStart3D(args, nargin, 5);
        if (nargin <= 4) { mrs::usage("ImPlot3D.PlotMesh", kSig_PlotMesh); return; }
        mrs::Faces fc;
        const unsigned* v_faces = mrs::getFaces(args[4], "faces", count, fc);
        int idxCount = fc.n;
        if (mrs::failed()) return;
        switch (cid) {
        case mxDOUBLE_CLASS: tp_PlotMesh_3<double>(nlhs, plhs, v_label, args, nargin, specAt, count, v_faces, idxCount); break;
        case mxSINGLE_CLASS: tp_PlotMesh_3<float>(nlhs, plhs, v_label, args, nargin, specAt, count, v_faces, idxCount); break;
        case mxINT8_CLASS: tp_PlotMesh_3<ImS8>(nlhs, plhs, v_label, args, nargin, specAt, count, v_faces, idxCount); break;
        case mxUINT8_CLASS: tp_PlotMesh_3<ImU8>(nlhs, plhs, v_label, args, nargin, specAt, count, v_faces, idxCount); break;
        case mxINT16_CLASS: tp_PlotMesh_3<ImS16>(nlhs, plhs, v_label, args, nargin, specAt, count, v_faces, idxCount); break;
        case mxUINT16_CLASS: tp_PlotMesh_3<ImU16>(nlhs, plhs, v_label, args, nargin, specAt, count, v_faces, idxCount); break;
        case mxINT32_CLASS: tp_PlotMesh_3<ImS32>(nlhs, plhs, v_label, args, nargin, specAt, count, v_faces, idxCount); break;
        case mxUINT32_CLASS: tp_PlotMesh_3<ImU32>(nlhs, plhs, v_label, args, nargin, specAt, count, v_faces, idxCount); break;
        case mxINT64_CLASS: tp_PlotMesh_3<ImS64>(nlhs, plhs, v_label, args, nargin, specAt, count, v_faces, idxCount); break;
        case mxUINT64_CLASS: tp_PlotMesh_3<ImU64>(nlhs, plhs, v_label, args, nargin, specAt, count, v_faces, idxCount); break;
        default: mrs::fail("psychimgui:Type", "ImPlot3D.PlotMesh: unsupported data class."); break;
        }
    } else {
        mrs::usage("ImPlot3D.PlotMesh", kSig_PlotMesh);
    }
}

extern const char kSig_PlotText[] =
    "PsychImGui('ImPlot3D.PlotText', text, x, y, z [, angle=0.0] [, pixOffset=[0 0]])";
void h_PlotText(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin < 4 || nargin > 6) { mrs::usage("PlotText", kSig_PlotText); return; }
    (void)nlhs; (void)plhs; (void)args;
    mrs::StrBuf<256> b_text;
    const char* v_text = "";
    v_text = mrs::toUtf8(args[0], "text", b_text);
    double v_x = (double)(0);
    v_x = (double)mrs::getScalar(args[1], "x");
    double v_y = (double)(0);
    v_y = (double)mrs::getScalar(args[2], "y");
    double v_z = (double)(0);
    v_z = (double)mrs::getScalar(args[3], "z");
    double v_angle = (double)(0.0);
    if (nargin > 4) v_angle = (double)mrs::getScalar(args[4], "angle");
    ImVec2 v_pix_offset = ImVec2(0,0);
    if (nargin > 5) { double t[2] = {0, 0}; mrs::getVec(args[5], "pixOffset", t, 2); v_pix_offset = ImVec2((float)t[0], (float)t[1]); }
    if (mrs::failed()) return;
    if (!mrs::implot3dPlotOpen()) { mrs::fail("psychimgui:Usage", "ImPlot3D.PlotText needs an open plot: call it between ImPlot3D.BeginPlot and ImPlot3D.EndPlot."); return; }
    ImPlot3D::PlotText(v_text, v_x, v_y, v_z, v_angle, v_pix_offset);
}

extern const char kSig_PlotToPixels[] =
    "pix = PsychImGui('ImPlot3D.PlotToPixels', x, y, z)";
void h_PlotToPixels(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin < 3 || nargin > 3) { mrs::usage("PlotToPixels", kSig_PlotToPixels); return; }
    (void)nlhs; (void)plhs; (void)args;
    double v_x = (double)(0);
    v_x = (double)mrs::getScalar(args[0], "x");
    double v_y = (double)(0);
    v_y = (double)mrs::getScalar(args[1], "y");
    double v_z = (double)(0);
    v_z = (double)mrs::getScalar(args[2], "z");
    if (mrs::failed()) return;
    if (!mrs::implot3dPlotOpen()) { mrs::fail("psychimgui:Usage", "ImPlot3D.PlotToPixels needs an open plot: call it between ImPlot3D.BeginPlot and ImPlot3D.EndPlot."); return; }
    ImVec2 ret = ImPlot3D::PlotToPixels(v_x, v_y, v_z);
    if (nlhs > 0) { double t[2] = {(double)ret.x, (double)ret.y}; plhs[0] = mrs::outVec(t, 2); }
}

extern const char kSig_GetPlotRectPos[] =
    "pos = PsychImGui('ImPlot3D.GetPlotRectPos')";
void h_GetPlotRectPos(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin != 0) { mrs::usage("GetPlotRectPos", kSig_GetPlotRectPos); return; }
    (void)nlhs; (void)plhs; (void)args;
    if (mrs::failed()) return;
    if (!mrs::implot3dPlotOpen()) { mrs::fail("psychimgui:Usage", "ImPlot3D.GetPlotRectPos needs an open plot: call it between ImPlot3D.BeginPlot and ImPlot3D.EndPlot."); return; }
    ImVec2 ret = ImPlot3D::GetPlotRectPos();
    if (nlhs > 0) { double t[2] = {(double)ret.x, (double)ret.y}; plhs[0] = mrs::outVec(t, 2); }
}

extern const char kSig_GetPlotRectSize[] =
    "size = PsychImGui('ImPlot3D.GetPlotRectSize')";
void h_GetPlotRectSize(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin != 0) { mrs::usage("GetPlotRectSize", kSig_GetPlotRectSize); return; }
    (void)nlhs; (void)plhs; (void)args;
    if (mrs::failed()) return;
    if (!mrs::implot3dPlotOpen()) { mrs::fail("psychimgui:Usage", "ImPlot3D.GetPlotRectSize needs an open plot: call it between ImPlot3D.BeginPlot and ImPlot3D.EndPlot."); return; }
    ImVec2 ret = ImPlot3D::GetPlotRectSize();
    if (nlhs > 0) { double t[2] = {(double)ret.x, (double)ret.y}; plhs[0] = mrs::outVec(t, 2); }
}

extern const char kSig_PushColormap[] =
    "PsychImGui('ImPlot3D.PushColormap', name)";
void h_PushColormap(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin < 1 || nargin > 1) { mrs::usage("PushColormap", kSig_PushColormap); return; }
    (void)nlhs; (void)plhs; (void)args;
    mrs::StrBuf<256> b_name;
    const char* v_name = "";
    v_name = mrs::toUtf8(args[0], "name", b_name);
    if (mrs::failed()) return;
    ImPlot3D::PushColormap(v_name);
}

extern const char kSig_PushColormapIndex[] =
    "PsychImGui('ImPlot3D.PushColormapIndex', cmap)";
void h_PushColormapIndex(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin < 1 || nargin > 1) { mrs::usage("PushColormapIndex", kSig_PushColormapIndex); return; }
    (void)nlhs; (void)plhs; (void)args;
    ImPlot3DColormap v_cmap = (ImPlot3DColormap)(0);
    v_cmap = (ImPlot3DColormap)mrs::getFlags(args[0], "cmap");
    if (mrs::failed()) return;
    ImPlot3D::PushColormap(v_cmap);
}

extern const char kSig_PopColormap[] =
    "PsychImGui('ImPlot3D.PopColormap' [, count=1])";
void h_PopColormap(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin < 0 || nargin > 1) { mrs::usage("PopColormap", kSig_PopColormap); return; }
    (void)nlhs; (void)plhs; (void)args;
    int v_count = (int)(1);
    if (nargin > 0) v_count = (int)mrs::getInt(args[0], "count");
    if (mrs::failed()) return;
    ImPlot3D::PopColormap(v_count);
}

extern const char kSig_GetColormapCount[] =
    "ret = PsychImGui('ImPlot3D.GetColormapCount')";
void h_GetColormapCount(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin != 0) { mrs::usage("GetColormapCount", kSig_GetColormapCount); return; }
    (void)nlhs; (void)plhs; (void)args;
    if (mrs::failed()) return;
    int ret = ImPlot3D::GetColormapCount();
    if (nlhs > 0) plhs[0] = mrs::outDouble((double)(ret));
}

extern const char kSig_GetColormapName[] =
    "ret = PsychImGui('ImPlot3D.GetColormapName', cmap)";
void h_GetColormapName(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin < 1 || nargin > 1) { mrs::usage("GetColormapName", kSig_GetColormapName); return; }
    (void)nlhs; (void)plhs; (void)args;
    ImPlot3DColormap v_cmap = (ImPlot3DColormap)(0);
    v_cmap = (ImPlot3DColormap)mrs::getFlags(args[0], "cmap");
    if (mrs::failed()) return;
    const char* ret = ImPlot3D::GetColormapName(v_cmap);
    if (nlhs > 0) plhs[0] = mrs::fromUtf8(ret);
}

extern const char kSig_SampleColormap[] =
    "ret = PsychImGui('ImPlot3D.SampleColormap', t [, cmap=-1])";
void h_SampleColormap(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin < 1 || nargin > 2) { mrs::usage("SampleColormap", kSig_SampleColormap); return; }
    (void)nlhs; (void)plhs; (void)args;
    float v_t = (float)(0);
    v_t = (float)mrs::getScalar(args[0], "t");
    ImPlot3DColormap v_cmap = (ImPlot3DColormap)(-1);
    if (nargin > 1) v_cmap = (ImPlot3DColormap)mrs::getFlags(args[1], "cmap");
    if (mrs::failed()) return;
    ImVec4 ret = ImPlot3D::SampleColormap(v_t, v_cmap);
    if (nlhs > 0) { double t[4] = {(double)ret.x, (double)ret.y, (double)ret.z, (double)ret.w}; plhs[0] = mrs::outVec(t, 4); }
}

extern const char kSig_StyleColorsAuto[] =
    "PsychImGui('ImPlot3D.StyleColorsAuto')";
void h_StyleColorsAuto(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin != 0) { mrs::usage("StyleColorsAuto", kSig_StyleColorsAuto); return; }
    (void)nlhs; (void)plhs; (void)args;
    if (mrs::failed()) return;
    ImPlot3D::StyleColorsAuto(NULL);
}

extern const char kSig_StyleColorsDark[] =
    "PsychImGui('ImPlot3D.StyleColorsDark')";
void h_StyleColorsDark(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin != 0) { mrs::usage("StyleColorsDark", kSig_StyleColorsDark); return; }
    (void)nlhs; (void)plhs; (void)args;
    if (mrs::failed()) return;
    ImPlot3D::StyleColorsDark(NULL);
}

extern const char kSig_StyleColorsLight[] =
    "PsychImGui('ImPlot3D.StyleColorsLight')";
void h_StyleColorsLight(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin != 0) { mrs::usage("StyleColorsLight", kSig_StyleColorsLight); return; }
    (void)nlhs; (void)plhs; (void)args;
    if (mrs::failed()) return;
    ImPlot3D::StyleColorsLight(NULL);
}

extern const char kSig_StyleColorsClassic[] =
    "PsychImGui('ImPlot3D.StyleColorsClassic')";
void h_StyleColorsClassic(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin != 0) { mrs::usage("StyleColorsClassic", kSig_StyleColorsClassic); return; }
    (void)nlhs; (void)plhs; (void)args;
    if (mrs::failed()) return;
    ImPlot3D::StyleColorsClassic(NULL);
}

extern const char kSig_PushStyleColor[] =
    "PsychImGui('ImPlot3D.PushStyleColor', idx, col)";
void h_PushStyleColor(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin < 2 || nargin > 2) { mrs::usage("PushStyleColor", kSig_PushStyleColor); return; }
    (void)nlhs; (void)plhs; (void)args;
    ImPlot3DCol v_idx = (ImPlot3DCol)(0);
    v_idx = (ImPlot3DCol)mrs::getFlags(args[0], "idx");
    ImVec4 v_col = ImVec4(0,0,0,1);
    { double t[4] = {0, 0, 0, 0}; mrs::getVec(args[1], "col", t, 4); v_col = ImVec4((float)t[0], (float)t[1], (float)t[2], (float)t[3]); }
    if (mrs::failed()) return;
    ImPlot3D::PushStyleColor(v_idx, v_col);
}

extern const char kSig_PopStyleColor[] =
    "PsychImGui('ImPlot3D.PopStyleColor' [, count=1])";
void h_PopStyleColor(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin < 0 || nargin > 1) { mrs::usage("PopStyleColor", kSig_PopStyleColor); return; }
    (void)nlhs; (void)plhs; (void)args;
    int v_count = (int)(1);
    if (nargin > 0) v_count = (int)mrs::getInt(args[0], "count");
    if (mrs::failed()) return;
    ImPlot3D::PopStyleColor(v_count);
}

extern const char kSig_PushStyleVar[] =
    "PsychImGui('ImPlot3D.PushStyleVar', idx, val)";
void h_PushStyleVar(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin < 2 || nargin > 2) { mrs::usage("PushStyleVar", kSig_PushStyleVar); return; }
    (void)nlhs; (void)plhs; (void)args;
    ImPlot3DStyleVar v_idx = (ImPlot3DStyleVar)(0);
    v_idx = (ImPlot3DStyleVar)mrs::getFlags(args[0], "idx");
    float v_val = (float)(0);
    v_val = (float)mrs::getScalar(args[1], "val");
    if (mrs::failed()) return;
    ImPlot3D::PushStyleVar(v_idx, v_val);
}

extern const char kSig_PushStyleVarVec2[] =
    "PsychImGui('ImPlot3D.PushStyleVarVec2', idx, val)";
void h_PushStyleVarVec2(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin < 2 || nargin > 2) { mrs::usage("PushStyleVarVec2", kSig_PushStyleVarVec2); return; }
    (void)nlhs; (void)plhs; (void)args;
    ImPlot3DStyleVar v_idx = (ImPlot3DStyleVar)(0);
    v_idx = (ImPlot3DStyleVar)mrs::getFlags(args[0], "idx");
    ImVec2 v_val = ImVec2(0,0);
    { double t[2] = {0, 0}; mrs::getVec(args[1], "val", t, 2); v_val = ImVec2((float)t[0], (float)t[1]); }
    if (mrs::failed()) return;
    ImPlot3D::PushStyleVar(v_idx, v_val);
}

extern const char kSig_PopStyleVar[] =
    "PsychImGui('ImPlot3D.PopStyleVar' [, count=1])";
void h_PopStyleVar(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin < 0 || nargin > 1) { mrs::usage("PopStyleVar", kSig_PopStyleVar); return; }
    (void)nlhs; (void)plhs; (void)args;
    int v_count = (int)(1);
    if (nargin > 0) v_count = (int)mrs::getInt(args[0], "count");
    if (mrs::failed()) return;
    ImPlot3D::PopStyleVar(v_count);
}

extern const char kSig_ShowDemoWindow[] =
    "open = PsychImGui('ImPlot3D.ShowDemoWindow' [, open=[]])";
void h_ShowDemoWindow(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin < 0 || nargin > 1) { mrs::usage("ShowDemoWindow", kSig_ShowDemoWindow); return; }
    (void)nlhs; (void)plhs; (void)args;
    bool v_p_open = false;
    bool has_p_open = (nargin > 0) && !mxIsEmpty(args[0]);
    if (has_p_open) v_p_open = mrs::getBool(args[0], "open");
    if (mrs::failed()) return;
    ImPlot3D::ShowDemoWindow(has_p_open ? &v_p_open : NULL);
    if (nlhs > 0) plhs[0] = mrs::outBool(v_p_open);
}

extern const char kSig_ShowMetricsWindow[] =
    "popen = PsychImGui('ImPlot3D.ShowMetricsWindow' [, popen=[]])";
void h_ShowMetricsWindow(int nlhs, mxArray** plhs, int nargin, const mxArray** args) {
    if (nargin < 0 || nargin > 1) { mrs::usage("ShowMetricsWindow", kSig_ShowMetricsWindow); return; }
    (void)nlhs; (void)plhs; (void)args;
    bool v_p_popen = false;
    bool has_p_popen = (nargin > 0) && !mxIsEmpty(args[0]);
    if (has_p_popen) v_p_popen = mrs::getBool(args[0], "popen");
    if (mrs::failed()) return;
    ImPlot3D::ShowMetricsWindow(has_p_popen ? &v_p_popen : NULL);
    if (nlhs > 0) plhs[0] = mrs::outBool(v_p_popen);
}

}  // namespace pig_implot3d
#endif  // PSYCHIMGUI_IMPLOT3D
